url: https://fitchain.io

# Site settings
title: fitchain
email: hello@bount.ai
description: "Decentralized private machine learning"
web: https://fitchain.io
codename: fitchain

# Team names, titles and social links
people:
- name: Francesco Gadaleta
  pic: 1
  position: Head of Research
  social:
    - title: twitter
      url: https://www.twitter.com/thisisfrag
    - title: github
      url: https://github.com/fgadaleta

- name: Daan Gerits
  pic: 2
  position: Chief Technology Officer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

- name: Math De Vriendt
  pic: 3
  position: UI Engineer
  social:
    - title: twitter
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/fitchain_io
  - title: github
    url: http://github.com/fitchain

# Postal address (add as many lines as necessary)
address:
  - line: 1 Stadsvest
  - line: 3000 Leuven Belgium

# Build settings
markdown: kramdown
permalink: pretty
